### ISSUE TITLE
Board fails to load when a snake has a freckled tail

### ISSUE THREAD

**Issue by JMTyler** [BattlesnakeOfficial/board#12]
The media server appears to have permissions misconfigured for the `freckled` tail.  If a snake has this tail, the board fails to load at all, reporting the following error in the console:

> Access to fetch at 'https://media.battlesnake.com/snakes/tails/freckled.svg' from origin 'https://board.battlesnake.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

All other tails seem to load properly.

**Comment by bvanvugt** [comment]
@JMTyler interesting, thanks for the issue. We're taking a look - do you have a specific game that exhibits this?

**Comment by JMTyler** [comment]
Sure! The last few I saw are too far back in my history to find, so I just spun up a fresh one: https://play.battlesnake.com/g/e9b0ef15-1e2f-43bd-91c0-166adb600170/

**Comment by bvanvugt** [comment]
Okay, weird. It's working for a few of us on this end:
<img width="1357" alt="Screenshot 2020-06-16 14 41 02" src="https://user-images.githubusercontent.com/1531419/84831057-84467800-afdf-11ea-8602-d62a3dd00b3c.png">

I made some CDN changes, can you retry it?

**Comment by JMTyler** [comment]
All good!  I had to hard-reset my cache after your CDN change, but the game board is now loading properly, freckled butt & all.  Thanks!

**Comment by bvanvugt** [comment]
Wonderful, glad to hear. Thanks for reaching out :)
