### ISSUE TITLE
Games that no longer exist constantly try to connect to the engine's web-socket

### ISSUE THREAD

**Issue by WeekendWarrior1** [BattlesnakeOfficial/board#13]
**How to replicate:**
Head to https://play.battlesnake.com/g/71638e34-6659-420e-9d01-658a00a42e80/ with your network tab open.

**What should happen:**
When the request to get the game engine comes back as a 404, the board should show some info on the front-end telling the end user that the game is no longer stored in the battlesnake backend, and not try and connect to the engine's websocket.

**What happens:**
![image](https://user-images.githubusercontent.com/5209758/86502743-d3ffae80-bde9-11ea-8acb-fa7b71793e52.png)
As long as the browser is open, the board will keep trying to connect to the websocket, once a second.

**Comment by bvanvugt** [comment]
@WeekendWarrior1 thanks for this, great catch. We've started archiving games more aggressively lately, so not surprised this came up.

I'm hoping @colinjfw or @brandonb927 could help with this, they understand the socket code better than I.

**Comment by brandonb927** [comment]
I can take a peek at this. My first thought on a solution is that when Play loads the page from the backend it could send an event to the board with type `NOT_FOUND` and the board could interpret this to mean don't attempt to connect to the engine websocket.

**Comment by brandonb927** [comment]
@bvanvugt I have a PR up if you'd like to take a look, I have been unable to test it locally however as I cannot get Engine running locally as there is no release binary available anymore.

**Comment by bvanvugt** [comment]
@WeekendWarrior1 this is fixed in prod now, thanks again for the report :)
