### ISSUE TITLE
Create an endpoint for retrieving Board version.

### ISSUE THREAD

**Issue by bvanvugt** [BattlesnakeOfficial/board#3]
**What is the problem?**
We're not sure what version of board is live in the wild.

**What is the solution?**
Other apps provide a `/version` endpoint that dumps the APP_VERSION environment variable.
Example: [engine.battlesnake.com/version](https://engine.battlesnake.com/version) -> `0.0.8`.
Let's add this to board as well.

**Other Notes**
* Endpoint should return the APP_VERSION environment variable if set. 
* If not set, return 'unknown'.
* Here's the go code we use in engine:
```go
func versionHandler(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	version := os.Getenv("APP_VERSION")
	if len(version) == 0 {
		version = "unknown"
	}
	fmt.Fprint(w, version)
}
```

**Comment by bvanvugt** [comment]
@brandonb927 hoping maybe you can tackle this, should be pretty simple.

**Comment by brandonb927** [comment]
@bvanvugt sounds like something I could do this week, will update in this space here.
