### ISSUE TITLE
Board seems to not handle invalid tails

### ISSUE THREAD

**Issue by bryan-gilbert** [BattlesnakeOfficial/board#8]
If there is a typo in a snake's tail type the board does not render.

Sample broken game
https://play.battlesnake.com/g/51dac76c-0f38-4798-85c8-eb375ba745e7/
The tail type for Zombie snake was  tailType = 'flecked' which is not correct.  The moment you press play of forward with this game the entire board disappears.

Once the tailType is corrected to 'freckled' then everything works again

**Comment by bryan-gilbert** [comment]
@bvanvugt Brad, where can i find more information on contributing to this project. I might be able to try and fix this issue.

**Comment by bvanvugt** [comment]
@bryan-gilbert Awesome. There's a contributing guide here: https://github.com/BattlesnakeOfficial/community/blob/master/CONTRIBUTING.md

For this particular issue, you probably want to start here:
https://github.com/BattlesnakeOfficial/board/blob/master/src/utils/engine-client.js#L47

**Comment by bvanvugt** [comment]
This was fixed by @WeekendWarrior1 in PR #9
